# Generated by Django 5.0.2 on 2024-02-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etapasApp', '0001_initial'),
        ('fasesApp', '0001_initial'),
        ('proyectosApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etapasApp.etapa')),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fasesApp.fases')),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectosApp.proyecto')),
            ],
        ),
    ]
