# Generated by Django 5.0.2 on 2024-02-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
