# Generated by Django 5.0.2 on 2024-03-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='published',
        ),
    ]
