# Generated by Django 5.0.2 on 2024-03-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapasApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='created_at',
        ),
    ]
